### PR TITLE
[master] KZOO-285: do not export inbound onnet recording variable to the other account

### PR DESCRIPTION
**Pull request by icehess**
Local extension should not export endpoint recoding variables on leg b since
that leg belongs to call's target account and not the originating account.

### CODE REVIEW

**Comment by lazedo** [comment]
This will prevent recording on loopback a-leg

**Comment by icehess** [comment]
Leg A? you mean from the endpoint? That would be started by `cf_resource` already. So the when offnet req comes to stepswitch it is already started recording, according to the log I saw when testing this.

If we don't remove this from here, then it creates duplicate in account A and also creates a recording on the other account (because it is in outbound-actions).

Anywa saying this  figured shouldn't we remove start call recording from `cf_resource` and move the logic to stepswitch?

In my test I only see one recording (offnet outbound) for the Leg A (inbound).

**Comment by icehess** [comment]
@lazedo hmm, sorry just notice you said loop-back-a. hmm so how we can export it in loop-back-a but not on b?

**Comment by icehess** [comment]
Closing this in favor of fixing this in callflow.

**Pull request closed without merging**
